# https://help.github.com/en/actions
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
# https://help.github.com/en/actions/reference/events-that-trigger-workflows
# https://crontab.guru/#0_*/1_*_*_*

name: Graph Updater

on:
  schedule:
    # Run every 3 hours in case data is updated more often than daily; schedule only works on master branch
    - cron: '0 0,3,6,9,12,15,18,21 * * *'
    # Run every 10 minutes
    #- cron: '*/10 * * * *'
  push:
    branches:
      - dev
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      source_csv_file: time_series_covid19_deaths_global.csv

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Get repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Install Python librarries
        run: |
          pip3 install setuptools
          pip3 install pandas
          pip3 install plotly

      - name: Fetch latest data file & update timestamp
        run: |
          curl -L -O "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/${source_csv_file}"
          printf '%s' "$(date +'%^a %Y-%^b-%d %T %Z')" > update_timestamp.txt

      - name: Generate graph DIV files (from interim CSV files)
        run: |
          averages=(0 3 5 15)

          for average in "${averages[@]}"; do
            echo "Generating files; average=${average}"

            echo 'create_daily_rates_csv...'
            python3 \
              ci/create_daily_rates_csv.py "${source_csv_file}" ${average}

            echo 'create_daily_rates_csv % population...'
            python3 \
              ci/create_daily_rates_csv.py "${source_csv_file}" ${average} \
              data/population.csv

            python3 ci/create_graph_div.py daily_mortality_averaged_${average}_days.csv graph_${average}_avg.div
            python3 ci/create_graph_div.py daily_mortality_averaged_${average}_days_pct.csv graph_${average}_avg_pct.div
          done

          ls -ltr

      - name: Upload files
        run: |
          git config --local user.email "ci@github.com"
          git config --local user.name "ci"
          git pull
          git add update_timestamp.txt graph_*.div
          git commit -m "CI update @ $(date)"
          git push
