# https://help.github.com/en/actions
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
# https://help.github.com/en/actions/reference/events-that-trigger-workflows
# https://crontab.guru/#0_*/1_*_*_*

name: Update 6871.github.io

on:
  schedule:
    # 1 minute past every hour
    - cron: '0 */1 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Get repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Install Python librarries
        run: |
          pip3 install setuptools
          pip3 install pandas
          pip3 install plotly

      - name: Fetch latest data file
        run: curl -L -O https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv

      - name: Create CSV file of daily mortality rates - no running average
        run: python3 ci/create_daily_rates_csv.py time_series_covid19_deaths_global.csv 0

      - name: Generate graph DIV file - no running average
        run: python3 ci/create_graph_div.py daily_mortality_averaged_0_days.csv 'COVID-19 Daily Mortality Rate By Country - raw data, no averaging' daily_mortality_averaged_0_days.div

      - name: Create CSV file of daily mortality rates - 3 day running average
        run: python3 ci/create_daily_rates_csv.py time_series_covid19_deaths_global.csv 3

      - name: Generate graph DIV file - 3 day running average
        run: python3 ci/create_graph_div.py daily_mortality_averaged_3_days.csv 'COVID-19 Daily Mortality Rate By Country - 3 day running average' daily_mortality_averaged_3_days.div

      - name: Create CSV file of daily mortality rates - 5 day running average
        run: python3 ci/create_daily_rates_csv.py time_series_covid19_deaths_global.csv 5

      - name: Generate graph DIV file - 5 day running average
        run: python3 ci/create_graph_div.py daily_mortality_averaged_5_days.csv 'COVID-19 Daily Mortality Rate By Country - 5 day running average' daily_mortality_averaged_5_days.div

      - name: Create CSV file of daily mortality rates - 15 day running average
        run: python3 ci/create_daily_rates_csv.py time_series_covid19_deaths_global.csv 15

      - name: Generate graph DIV file - 15 day running average
        run: python3 ci/create_graph_div.py daily_mortality_averaged_15_days.csv 'COVID-19 Daily Mortality Rate By Country - 15 day running average' daily_mortality_averaged_15_days.div

      - name: Generate HTML file
        run: ./ci/create_html_file.sh wip.html daily_mortality_averaged_0_days.div daily_mortality_averaged_3_days.div daily_mortality_averaged_5_days.div daily_mortality_averaged_15_days.div

      - name: Commit and push HTML file
        run: |
          git config --local user.email "ci@github.com"
          git config --local user.name "ci"
          git add wip.html
          git commit -m "CI generated wip.html @ $(date)"
          git push
