# https://help.github.com/en/actions
#  https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

name: Data Refresh

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Generate HTML
        run: printf '<html><body><p>Hello, World @ %s!</p></body></html>' "$(date)" > hw.html

      - name: Dump HTML
        run: cat hw.html

      - name: Commit html file
        run: |
          git config --local user.email "ci@github.com"
          git config --local user.name "ci"
          git add hw.html
          git commit -m "Action commit of hw.html"
          echo 'Boo!'

      - name: Push html file
        run: |
          git push
